### ISSUE TITLE
TestIndexDocuments fails on at least Windows

### ISSUE THREAD

**Issue by kwalcock** [lum-ai/odinson#185]
Running this test in sbt results in this:
```
[info] - should get the correct list of files *** FAILED *** (1 second, 32 milliseconds)
[info]   java.nio.file.InvalidPathException: Illegal char <:> at index 2: /E:/Users/kwa/Clients/lum/Projects/odinson-project/odinson/extra/target/scala-2.12/test-classes//index
[info]   at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
[info]   at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[info]   at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[info]   at sun.nio.fs.WindowsPath.parse(Unknown Source)
[info]   at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
[info]   at java.nio.file.Paths.get(Unknown Source)
[info]   at ai.lum.odinson.OdinsonIndexWriter$.fromConfig(OdinsonIndexWriter.scala:269)
[info]   at ai.lum.odinson.extra.IndexDocuments$.delayedEndpoint$ai$lum$odinson$extra$IndexDocuments$1(IndexDocuments.scala:40)
[info]   at ai.lum.odinson.extra.IndexDocuments$delayedInit$body.apply(IndexDocuments.scala:16)
[info]   at scala.Function0.apply$mcV$sp(Function0.scala:39)
[info]   ...
```
I would debug it, except the subproject doesn't seem to load correctly in IntelliJ.  An attempt to run that test results in this:
```
Unable to load a Suite class. This could be due to an error in your runpath. Missing class: ai.lum.odinson.extra.TestIndexDocuments
java.lang.ClassNotFoundException: ai.lum.odinson.extra.TestIndexDocuments
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$6(Runner.scala:1213)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$6$adapted(Runner.scala:1211)
	at scala.collection.TraversableLike.noneIn$1(TraversableLike.scala:271)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:337)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:249)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:347)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:347)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1211)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:40)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```
If someone happens to know what that's about, then I can go ahead and deal with Windows.  If not, I can probably do both eventually.

**Comment by kwalcock** [comment]
IntelliJ seems to be working again, so I can work on the other problem.

**Comment by kwalcock** [comment]
See #191.
