### ISSUE TITLE
Basic queries generate errors

### ISSUE THREAD

**Issue by danebell** [lum-ai/odinson#300]
**Describe the bug**
A simple basic query generates an error in the API (and probably elsewhere?).

**To Reproduce**
1. Go to https://api-test.odinson.lum.ai/api#/core/search
2. Click on 'Try it out' for `/api/execute/pattern`
3. In the query field, enter `[lemma=insect] <nsubj [lemma=ingest]`. Remove the parent query provided by default.
4. Click 'Execute'.
5. See error.

**Expected behavior**
A list of results (which could be empty) returned in JSON format.

**Comment by myedibleenso** [comment]
Can you include the the stack trace, @danebell?

**Comment by BeckySharp** [comment]
I can replicate this, here's the trace:
``` 
"error": "java.lang.NullPointerException
	at ai.lum.odinson.lucene.search.GraphTraversalSpans.twoPhaseCurrentDocMatches(GraphTraversalQuery.scala:132)
	at ai.lum.odinson.lucene.search.spans.ConjunctionSpans$$anon$1.matches(ConjunctionSpans.scala:87)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:253)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:197)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:668)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:472)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:591)
	at ai.lum.odinson.lucene.search.OdinsonIndexSearcher.odinSearch(OdinsonIndexSearcher.scala:76)
	at ai.lum.odinson.ExtractorEngine.query(ExtractorEngine.scala:203)
	at ai.lum.odinson.ExtractorEngine.query(ExtractorEngine.scala:146)
	at ai.lum.odinson.ExtractorEngine.query(ExtractorEngine.scala:126)
	at controllers.OdinsonController.retrieveResults(OdinsonController.scala:788)
	at controllers.OdinsonController.$anonfun$runQuery$2(OdinsonController.scala:893)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by BeckySharp** [comment]
I'll make the test and go from there

**Comment by danebell** [comment]
I reindexed the Odinson docs that were on the API server, but that alone didn't seem to solve it. I don't understand very well how the docker image works, but I believe it will look in the new files at the same location. That might mean the documents need to be reparsed from the text (which is also on the server).

**Comment by danebell** [comment]
I reindexed the documents on the API server and restarted the docker. This has addressed the problem. @myedibleenso, I will try to update this index on our s3 bucket (the pbi one, right?).
