### ISSUE TITLE
Only 20 Sentences Returned via REST API

### ISSUE THREAD

**Issue by bflashcp3f** [lum-ai/odinson#315]
**How can we help you?**
Thank you for open-sourcing this useful software! I am currently working on a semantic search demo, which uses odinson to retrieve sentences via the REST API (/api/execute/pattern). However, it seems that no matter what query I use, it only returns at most 20 sentences in "scoreDocs" while the value of "totalHits" is much larger. I don't find any parameter that controls the number of sentences returned. Is there a way that I can get all the matched sentences? Thank you very much!

Best,
-Fan

**Comment by danebell** [comment]
Hi, Fan. If you're running your own REST instance, you can change this setting in the [core configuration file](https://github.com/lum-ai/odinson/blob/ed7de8422a67e335f2e4f36e1a453cd8774892ce/core/src/main/resources/reference.conf#L16). Thanks for your interest!

**Comment by bflashcp3f** [comment]
Thanks for the quick reply! Just to double-check: once I change this "pageSize" parameter, I need to re-compile the project using the command `sbt compile`, and then I can launch the REST API again, and it should work from there?

**Comment by danebell** [comment]
Under normal circumstances, the API uses live reloading, so you don't even need to restart the API. It will detect changes to your configuration live and update on the next API call.

**Comment by bflashcp3f** [comment]
Thanks for the explanation! It worked after I re-compiled and dockerized again. For REST API, the only way I find on the official document (http://gh.lum.ai/odinson/restapi.html) to run it is using the docker image, so is there any way that I can run REST API without using the docker image?

**Comment by danebell** [comment]
Certainly. If you have your configuration set up as you like it, you can run the API from the terminal by navigating to the `odinson` repository folder and entering `sbt backend/run` to start the Play application. The docker image is just more transportable.

**Comment by bflashcp3f** [comment]
Thanks for the explanation! I ran the command you mentioned and got the following response.
```
bai (master *) odinson $ sbt backend/run
java.io.IOException: Read-only file system
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(File.java:2129)
	at java.base/java.io.File.createTempFile(File.java:2175)
	at sbt.StandardMain$.$anonfun$initialGlobalLogging$1(Main.scala:156)
	at sbt.internal.util.GlobalLogBacking$.apply(GlobalLogging.scala:58)
	at sbt.internal.util.GlobalLogging$.initial(GlobalLogging.scala:85)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:157)
	at sbt.StandardMain$.initialState(Main.scala:183)
	at sbt.xMain.run(Main.scala:87)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.io.IOException: Read-only file system
```

**Comment by danebell** [comment]
You're welcome. Thanks for your interest!
